# fly.toml app configuration file generated for pdstuber-dev on 2024-01-06T23:12:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdstuber-dev"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8043
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
